CREATE TABLE IF NOT EXISTS bans (
  roblox_id BIGINT NOT NULL UNIQUE PRIMARY KEY,
  added TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  countdown_start BIGINT DEFAULT 0 NOT NULL,
  unbanned_at BIGINT NOT NULL,
  reason VARCHAR(1000) NOT NULL,
  log_id VARCHAR(100) DEFAULT ""
)
